Fix broken links
codelikeagirlau/accessibility-resources pull request #62
Opened 2023-10-31 05:28 UTC by Shannspan

Hi! 

I've fixed all the links accross all html pages. 

Also updated each html page to  have correct class ="active" on it's own link.

Also have noticed that we don't appear to have a link from the main sidebar nav to sub-page/accessibility-course.html. Is there a link in another location so the user can access it?

2023-10-31 06:00 UTC, sarahesbie commented
Heya @Shannspan can you have a look at resolving the merge conflict? let us know if you need help.
I think the courses page is linked from the home page, but it could be good to have it linked in the sidebar too!

2023-10-31 06:03 UTC, sarahesbie requested changes
Heya @Shannspan ! Super annoying link edit request due to github pages!!

2023-10-31 06:03 UTC, sarahesbie commented on about.html
Heya @Shannspan this is super annoying but can you update all of your links to be like this:
`<a href="accessibility-resources/tools-and-resources.html">`

for some reason GitHub pages has an issue with the preceding slash, ie.e the below won't work:
`<a href="/accessibility-resources/tools-and-resources.html">`

2023-10-31 06:03 UTC, sarahesbie commented on index.html
see comment about links above

2023-10-31 06:03 UTC, sarahesbie commented on index.html
see comment about links above

2023-10-31 06:03 UTC, sarahesbie commented on manifesto.html
see comment about links above

2023-10-31 06:03 UTC, sarahesbie commented on sub-page/accessibility-course.html
see comment about links above

2023-10-31 06:03 UTC, sarahesbie commented on sub-page/web-developer-pledge.html
see comment about links above

2023-10-31 06:03 UTC, sarahesbie commented on template.html
see comment about links above

2023-10-31 06:03 UTC, sarahesbie commented on tools-and-resources.html
see comment about links above

2023-10-31 06:31 UTC, Shannspan commented
Interesting - will do!

2023-10-31 06:34 UTC, Shannspan commented
@sarahesbie - just to check: 

I didn't remove the leading '/' because when I go live from VS code the links don't work without it. 

Do you still want me to go ahead or is more investigation needed?

2023-10-31 06:41 UTC, Shannspan commented
Actually - just did a bit of research myself and I can see now that the leading '/' should fix the relative path issue in github. Just confusing in terms of testing the links on the local host! I'll get to it a bit later this afternoon :)

2023-10-31 09:29 UTC, Shannspan commented
Hi @sarahesbie the additional commit is because I just realised I hadn't saved changes to the tools-and-resources. html file. All html files should have their nav menu links updated now.

2023-10-31 21:31 UTC, sarahesbie approved these changes

2023-10-31 21:32 UTC, sarahesbie commented
@Shannspan looks like you've still got a merge conflict! I'm not at my computer today but can approve PRs from my phone.

2023-11-03 08:27 UTC, Shannspan commented
OK - @sarahesbie - I'm really really hoping hat I 'resolved' that correctly! 😬

2023-11-05 22:47 UTC, merged